export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: string;
};

export type Image = {
  __typename?: 'Image';
  clipSkip?: Maybe<Scalars['Int']>;
  createdAt: Scalars['ISO8601DateTime'];
  description?: Maybe<Scalars['String']>;
  height?: Maybe<Scalars['Int']>;
  id: Scalars['ID'];
  imageSrc?: Maybe<Scalars['String']>;
  keyword?: Maybe<Scalars['String']>;
  model?: Maybe<Scalars['String']>;
  negativePrompt?: Maybe<Scalars['String']>;
  prompt?: Maybe<Scalars['String']>;
  sampler?: Maybe<Scalars['String']>;
  scale?: Maybe<Scalars['Float']>;
  seed?: Maybe<Scalars['Float']>;
  steps?: Maybe<Scalars['Int']>;
  updatedAt: Scalars['ISO8601DateTime'];
  url?: Maybe<Scalars['String']>;
  userId: Scalars['Int'];
  width?: Maybe<Scalars['Int']>;
};

/** Autogenerated input type of ImageCreate */
export type ImageCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  imageInput: ImageInput;
};

/** Autogenerated return type of ImageCreate. */
export type ImageCreatePayload = {
  __typename?: 'ImageCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  image: Image;
};

/** Autogenerated input type of ImageDelete */
export type ImageDeleteInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of ImageDelete. */
export type ImageDeletePayload = {
  __typename?: 'ImageDeletePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  image: Image;
};

export type ImageInput = {
  clipSkip?: InputMaybe<Scalars['Int']>;
  createdAt?: InputMaybe<Scalars['ISO8601DateTime']>;
  description?: InputMaybe<Scalars['String']>;
  height?: InputMaybe<Scalars['Int']>;
  id?: InputMaybe<Scalars['ID']>;
  imageSrc?: InputMaybe<Scalars['String']>;
  keyword?: InputMaybe<Scalars['String']>;
  model?: InputMaybe<Scalars['String']>;
  negativePrompt?: InputMaybe<Scalars['String']>;
  prompt?: InputMaybe<Scalars['String']>;
  sampler?: InputMaybe<Scalars['String']>;
  scale?: InputMaybe<Scalars['Float']>;
  seed?: InputMaybe<Scalars['Float']>;
  steps?: InputMaybe<Scalars['Int']>;
  updatedAt?: InputMaybe<Scalars['ISO8601DateTime']>;
  url?: InputMaybe<Scalars['String']>;
  userId?: InputMaybe<Scalars['Int']>;
  width?: InputMaybe<Scalars['Int']>;
};

/** Autogenerated input type of ImageUpdate */
export type ImageUpdateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  imageInput: ImageInput;
};

/** Autogenerated return type of ImageUpdate. */
export type ImageUpdatePayload = {
  __typename?: 'ImageUpdatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  image: Image;
};

export type Mutation = {
  __typename?: 'Mutation';
  /** Creates a new image */
  imageCreate?: Maybe<ImageCreatePayload>;
  /** Deletes a image by ID */
  imageDelete?: Maybe<ImageDeletePayload>;
  /** Updates a image by id */
  imageUpdate?: Maybe<ImageUpdatePayload>;
  /** Creates a new user */
  userCreate?: Maybe<UserCreatePayload>;
  /** Deletes a user by ID */
  userDelete?: Maybe<UserDeletePayload>;
  /** Updates a user by id */
  userUpdate?: Maybe<UserUpdatePayload>;
};


export type MutationImageCreateArgs = {
  input: ImageCreateInput;
};


export type MutationImageDeleteArgs = {
  input: ImageDeleteInput;
};


export type MutationImageUpdateArgs = {
  input: ImageUpdateInput;
};


export type MutationUserCreateArgs = {
  input: UserCreateInput;
};


export type MutationUserDeleteArgs = {
  input: UserDeleteInput;
};


export type MutationUserUpdateArgs = {
  input: UserUpdateInput;
};

export type Query = {
  __typename?: 'Query';
  /** List all users */
  allUsers: Array<User>;
  /** Clear User Sessions */
  clearUserSessions?: Maybe<Scalars['String']>;
  imageById: Image;
  imagesByKeyword: Array<Image>;
  /** Login a user */
  login?: Maybe<Scalars['String']>;
  /** Logout a user */
  logout: Scalars['Boolean'];
  userById: User;
};


export type QueryClearUserSessionsArgs = {
  email: Scalars['String'];
  password: Scalars['String'];
};


export type QueryImageByIdArgs = {
  id: Scalars['ID'];
};


export type QueryImagesByKeywordArgs = {
  keyword: Scalars['String'];
};


export type QueryLoginArgs = {
  email: Scalars['String'];
  password: Scalars['String'];
};


export type QueryUserByIdArgs = {
  id: Scalars['ID'];
};

export type User = {
  __typename?: 'User';
  avatarUrl?: Maybe<Scalars['String']>;
  biography?: Maybe<Scalars['String']>;
  createdAt: Scalars['ISO8601DateTime'];
  email?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  images?: Maybe<Array<Image>>;
  password?: Maybe<Scalars['String']>;
  updatedAt: Scalars['ISO8601DateTime'];
  username?: Maybe<Scalars['String']>;
};

/** Autogenerated input type of UserCreate */
export type UserCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  userInput: UserInput;
};

/** Autogenerated return type of UserCreate. */
export type UserCreatePayload = {
  __typename?: 'UserCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

/** Autogenerated input type of UserDelete */
export type UserDeleteInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of UserDelete. */
export type UserDeletePayload = {
  __typename?: 'UserDeletePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export type UserInput = {
  avatarUrl?: InputMaybe<Scalars['String']>;
  biography?: InputMaybe<Scalars['String']>;
  createdAt?: InputMaybe<Scalars['ISO8601DateTime']>;
  email?: InputMaybe<Scalars['String']>;
  id?: InputMaybe<Scalars['ID']>;
  password?: InputMaybe<Scalars['String']>;
  updatedAt?: InputMaybe<Scalars['ISO8601DateTime']>;
  username?: InputMaybe<Scalars['String']>;
};

/** Autogenerated input type of UserUpdate */
export type UserUpdateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  userInput: UserInput;
};

/** Autogenerated return type of UserUpdate. */
export type UserUpdatePayload = {
  __typename?: 'UserUpdatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};
