source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'rails', '~> 7.0', '>= 7.0.4.2'
gem 'pg', '~> 1.4', '>= 1.4.5'
gem 'puma', '~> 6.0', '>= 6.0.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'bcrypt', '~> 3.1', '>= 3.1.18'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]

  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
  gem 'rubocop', require: false
  gem 'rubocop-graphql', '~> 0.19.0'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'

  gem 'spring-commands-rspec'
end

gem 'graphiql-rails', '~> 1.8'
gem 'graphql', '~> 2.0', '>= 2.0.16'

gem 'rack-cors', '~> 1.1', '>= 1.1.1'
